---
- name: Sending notification email
  mail:
    host: "{{ email_server }}"
    port: "{{ email_server_port }}"
    username: "{{ email_username }}"
    password: "{{ email_password }}"
    from: "{{ email_from_address }}"
    to: "{{ email_to_address }}"
    #cc: "{{ email_cc_address }}"
    subject: "{{ email_subject }}"
    body: "{{ email_report_body }}"
    #attach:
    #  - "{{ report_file_name }}"
    headers:
      - Reply-To="{{ email_replyto_address }}"
    secure: try
  delegate_to: localhost